### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mgermain** [mgermain/ECODSEdataset-fun-time#29]
- [ ] Build the doc automatically with sphinx
- [ ] Host the doc on readthedoc
- [ ] Have a 100% code coverage
- [ ] Basic use of MLFlow
- [ ] Setup and basic use of Orion

**Comment by mgermain** [comment]
[Trains](https://github.com/allegroai/trains) is possibly a better option than MLFlow
